apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test-jc-ingress
  namespace: testjc
spec:
  ingressClassName: traefik
  rules:
    - host: test.lab.jcheype.com
      http:
        paths:
          - backend:
              service:
                name: test-jc
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
